trigger: none

pr: none

variables:
  devOpsServiceConnection: "Obelisk Frontend Subscription" # As it stands in Azure DevOps

resources:
  pipelines:
    - pipeline: build-ci
      source: 'Obelisk Frontend Vuetify Build CI'
      trigger:
        branches:
          include:
            - main

stages:
  - stage: Set_Deployment_Number
    displayName: 'Set Deployment Number'
    jobs:
      - job:
        steps:
          - checkout: none
          - bash: |
              echo "##vso[build.updatebuildnumber]$(resources.pipeline.build-ci.runName)"
            displayName: 'Set Deployment Number'

  - stage: Deploy_To_QA
    displayName: 'QA'
    dependsOn: [ Set_Deployment_Number ]
    jobs:
      - template: 'rollout-deploy-stage-jobs.yml'
        parameters:
          buildArtifactPipelineId: build-ci
          projectCode: 'obelisk' # It has to be passed as a literal or parameter value
          stageCode: 'qa'
          devOpsEnvironment: 'Obelisk UI QA'
          devOpsServiceConnection: $(devOpsServiceConnection)
          runtimeEnvironment: 'qa'

  - stage: Deploy_To_UAT
    displayName: 'UAT'
    dependsOn: [ Deploy_To_QA ]
    jobs:
      - template: 'rollout-deploy-stage-jobs.yml'
        parameters:
          buildArtifactPipelineId: build-ci
          projectCode: 'obelisk' # It has to be passed as a literal or parameter value
          stageCode: 'uat'
          devOpsEnvironment: 'Obelisk UI UAT'
          devOpsServiceConnection: $(devOpsServiceConnection)
          runtimeEnvironment: 'uat'          
