export default {
    en: {
        application: {
            applicationName: "Obelisk Template",
            developedBy: "Developed by",
            version: "Version",
            language: "English"
        },
        button: {
            add: "Add",
            quickAdd: "Quick Add",
            authSettings: "Authentication settings",
            cancel: "Cancel",
            changePassword: "Change password",
            change: "Change",
            close: "Close",
            createNew: "Create new",
            delete: "Delete",
            download: "Download",
            edit: "Edit",
            export: "Export",
            exportExcel: "Export as Excel",
            exportPdf: "Export as PDF",
            save: "Save changes",
            resetPassword: "Reset password",
            yes: "Yes",
            no: "No",
            remove: "Remove",
            upload: "Upload",
            signOut: "Sign out",
            signIn: "Sign in",
            unlock: "Unlock",
            submit: "Submit",
            viewDetails: "View Details",
            update: "Update",
            copy: "Copy",
            select: "Select",
            back: "Back",
            backToSignIn: "Back to sign in page",
            goToHome: "Back to Home"
        },
        imageAltText: {
            entityImage: "Entity image",
            logoImage: "Obelisk Template Homepage"
        },
        layout: {
            bannerTitle: "Obelisk Template",
            dashboard: "Dashboard",
            users: "Users",
            fileManager: "File Manager",
            anemicModel: "Anemic Model",
            anemicCustomers: "Customers",
            anemicProducts: "Products",
            anemicPurchaseOrders: "Purchase Orders",
            anemicTags: "Tags",
            richModel: "Rich Model",
            richCustomers: "Customers",
            richProducts: "Products",
            richPurchaseOrders: "Purchase Orders",
            richTags: "Tags",
            changePassword: "Change Password",
            logout: "Logout",
            authenticationSettings: "Authentication Settings",
            navigation: "Navigation"
        },
        message: {
            addEntityTitle: "Add",
            editEntityTitle: "Edit",
            deleteEntityTitle: "Delete",
            search: "Search",
            currentFolder: "Current folder:",
            yes: "Yes",
            no: "No",
            itemsInCollection: "items in collection",
            noElementsFound: "No elements found",
            fieldRequired: "Required",
            maxCharacters: "Must be less than {max} characters",
            maxNumbers: "Must be less than {max}",
            minCharacters: "Must be {min} or more characters",
            minNumbers: "Must be {min} or more",
            email: "Invalid email format",
            phone: "Phone number must start with '0' and be 10 or 11 digits long",
            afterToday: "Must be today or after"
        },
        notifications: {
            successTitle: "Upload Successful",
            successMessage: "File was uploaded successfully",
            failTitle: "Upload Failed",
            failMessage: "File was not uploaded successfully, please try again",
            pageNotFound: "Oops! Page not found"
        },
        placeholder: {
            multiSelectSearch: "Type to search",
            multiSelectSearchSelect: "Press enter to select",
            multiSelectSearchSelected: "Selected",
            multiSelectSearchDeselect: "Press enter to remove",
            select: "- Select -",
            multiSelectSearchAddYourOwn: "Type to search or add your own",
            search: "Search...",
            imageDrop: "Drop image here or",
            fileDrop: "Drop file here or",
            clickToUpload: "click to upload",
            pleaseSelect: "Please select...",
            pickADate: "Pick a date",
            rangeSeparator: "To",
            startDate: "Start date",
            endDate: "End date"
        },
        password: {
            unknownError: "An unknown error has occured",
            backToLogin: "Back to login page",
            passwordChanged: "The password has been successfully changed",
            email: "Email"
        }
    }
};
