export default {
    en: {
        application: {
            applicationName: "Obelisk Template",
            developedBy: "Developed by",
            build: "Build",
            version: "Version",
            language: "English",
        },
        button: {
            authSettings: "Authentication settings",
            cancel: "Cancel",
            changePassword: "Change password",
            change: "Change",
            close: "Close",
            createNew: "Create new",
            delete: "Delete",
            download: "Download",
            edit: "Edit",
            export: "Export",
            exportExcel: "Export as Excel",
            exportPdf: "Export as PDF",
            save: "Save changes",
            resetPassword: "Reset password",
            yes: "Yes",
            no: "No",
            remove: "Remove",
            upload: "Upload",
            signOut: "Sign out",
            signIn: "Sign in",
            unlock: "Unlock",
            submit: "Submit",
            viewDetails: "View Details",
            update: "Update",
            copy: "Copy",
            select: "Select",
            back: "Back",
            backToSignIn: "Back to sign in page",
            goToHome: "Back to Home",
        },
        imageAltText: {
            entityImage: "Entity image",
            logoImage: "Obelisk Template Homepage",
        },
        layout: {
            dashboard: "Dashboard",
            users: "Users",
            fileManager: "File Manager",
            anemicModel: "Anemic Model",
            anemicCustomers: "Customers",
            anemicProducts: "Products",
            anemicPurchaseOrders: "Purchase Orders",
            anemicTags: "Tags",
            richModel: "Rich Model",
            richCustomers: "Customers",
            richProducts: "Products",
            richPurchaseOrders: "Purchase Orders",
            richTags: "Tags",
            changePassword: "Change Password",
            logout: "Logout",
            authenticationSettings: "Authentication Settings",
            navigation: "Navigation",
        },
        message: {
            addEntityTitle: "Add",
            editEntityTitle: "Edit",
            deleteEntityTitle: "Delete",
            search: "Search",
            currentFolder: "Current folder:",
            yes: "Yes",
            no: "No",
            itemsInCollection: "items in collection",
            noElementsFound: "No elements found",
        },
        notifications: {
            successTitle: "Upload Successful",
            successMessage: "File was uploaded successfully",
            failTitle: "Upload Failed",
            failMessage: "File was not uploaded successfully, please try again",
            pageNotFound: "Oops! Page not found",
            success: "Success",
        },
        placeholder: {
            multiSelectSearch: "Type to search",
            multiSelectSearchSelect: "Press enter to select",
            multiSelectSearchSelected: "Selected",
            multiSelectSearchDeselect: "Press enter to remove",
            select: "- Select -",
            multiSelectSearchAddYourOwn: "Type to search or add your own",
            search: "Search...",
            imageDrop: "Drop image here or",
            fileDrop: "Drop file here or",
            clickToUpload: "click to upload",
            pleaseSelect: "Please select...",
            pickADate: "Pick a date",
            rangeSeparator: "To",
            startDate: "Start date",
            endDate: "End date",
        },
        password: {
            unknownError: "An unknown error has occurred",
            backToLogin: "Back to login page",
            passwordChanged: "The password has been successfully changed",
            resetPasswordInvalidToken: "The URL is either invalid or has expired",
            email: "Email",
            defaultError: "An error occured while trying to log you in.",
            authAddError: "An error occured while trying to add authenticator.",
        },
        errors: {
            error: "Error",
        },
        validation: {
            email: "Invalid email format.",
            maxCharacters: "The input field must contain less than {max} characters.",
            maxNumber: "The input field must be less than {max}.",
            minCharacters: "The input field must contain at least {min} characters.",
            minNumber: "The input field must be at least {min}.",
            lengthCharacters: "The input field must be {length} characters long.",
            maxDateInvalid: "Date must be before {limit}.",
            minDateInvalid: "Date must be after {limit}.",
            phone: "Phone number must start with '0' and be 10 or 11 digits long.",
            afterToday: "The input field must be today or after",
            alphaDash: "The input field must only contain alphabetic characters, numbers, dashes or underscores.",
            numeric: "The input field must be numeric.",
            required: "Required.",
            requiresDigit: "The input field must contain at least one digit.",
            requiresNonAlphanumeric: "The input field must contain at least one special character.",
            requiresCapital: "The input field must contain at least one capital letter.",
            requiresNonCapital: "The input field must contain at least one non-capital character.",
            requiresUniqueCharacters: "The input field must contain at least {count} unique characters.",
            requiresPasswordMatch: "The passwords must match.",
        },
    },
};
