name: "Check PR"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.head_ref}}"
  cancel-in-progress: true

jobs:
  build_and_test:
    name: "Build & Lint"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm run lint