name: "Check PR"

on:
  push:
    branches:
      - "addPrGithubAction"
    paths:
      - "src/**"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.head_ref}}"
  cancel-in-progress: true

jobs:
  build_and_test:
    name: "Build & Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - run: |
              npm ci
              npm run build
              npm run lint
